name: Push to rubygems.org

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          rubygems: latest
          bundler-cache: true
      - uses: rubygems/release-gem@v1
